export const CALCULATOR_CHANGE = {
    CALCULATE: 'CALCULATE',
    RESET_CALCULATION: 'RESET_CALCULATION',
    COMMISSION: .0025,
    VAT: .12,
    SCCP: 0.0001,
    TRANSACTION_FEE: 0.00005,
    SALES_TAX: 0.006
}